#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ttrss"
name = "Tiny Tiny RSS"
description.en = "News feed (RSS/Atom) reader and aggregator"
description.fr = "Lecteur de flux d’actualité utilisant les protocoles RSS et Atom"

version = "2026.08.06~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
admindoc = "https://github.com/tt-rss/tt-rss/wiki"
code = "https://github.com/tt-rss/tt-rss"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ttrss"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]

    url = "https://github.com/tt-rss/tt-rss/archive/f0d6de8c0be610583993e3c1e75a40bbb6fc6ffa.tar.gz"
    sha256 = "aaeed3750d33a6bace9bdf3a65676f9fec48b2e6496321f140cb4c5817fc353d"
    
    autoupdate.upstream = "https://github.com/tt-rss/tt-rss"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    public.url = "/public.php"
    public.allowed = "visitors"
    public.show_tile = false
    public.protected = true

    api.url = "/api"
    api.auth_header =false
    api.show_tile = false
    api.protected = true
    api.allowed = "visitors"

    [resources.apt]
    packages = "postgresql, php8.5-pgsql, php8.5-curl, php8.5-gd, php8.5-fileinfo, php8.5-intl, php8.5-cli, php8.5-mbstring, php8.5-xml"

    [resources.database]
    type = "postgresql"
