#!/bin/bash

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

# The last parameter is the id of the app instance
app=${!#}

domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)

# Copy the app files
final_path="/var/www/$app"
sudo cp -a "$final_path" ./www

# Copy the conf files
sudo mkdir -p ./conf
sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf ./conf/nginx.conf
sudo cp -a /etc/cron.d/$app ./conf/cron

# Backup db
root_pwd=$(sudo cat /etc/yunohost/mysql)
sudo su -c "mysqldump -u root -p$root_pwd --no-create-db $app > ./db.sql"
