#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Load common variables
source ./_common.sh


# Retrieve arguments
domain=$1
path=$2
app=${!#}

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
exit 1
fi

# Generate random DES key & password
deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Copy files to the right place
final_path=/var/www/$app
sudo mkdir -p $final_path
extract_ttrss $final_path
sudo cp ../conf/config.php $final_path/
sudo cp ../conf/*.patch /tmp/
sudo patch -d $final_path -p0 < /tmp/update.patch
sudo patch -d $final_path/plugins/auth_remote/ -p0 < /tmp/init.patch

# Use 'ttrss' as database name and user
db_user=$app

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd -s $(readlink -e $final_path/schema/ttrss_schema_mysql.sql)
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Change variables in ttrss configuration
sudo sed -i "s/yunouser/$db_user/g" $final_path/config.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/config.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/config.php
sudo sed -i "s,yunopath,https://$domain$path,g" $final_path/config.php
echo "*/30 * * * * www-data cd $final_path && /usr/bin/php $final_path/update.php --feeds >/dev/null 2>&1" > /tmp/cronttrss
sudo mv /tmp/cronttrss /etc/cron.d/$app
sudo chown root /etc/cron.d/$app
sudo apt-get install php5-cli -y

#add folder
for i in export images upload js
do
  if [ ! -d $final_path/cache/$i ];
  then
    sudo mkdir $final_path/cache/$i
  fi
  sudo chmod -R 777 $final_path/cache/$i
done

for i in feed-icons lock
do
  if [ ! -d $final_path/$i ];
  then
    sudo mkdir $final_path/$i
  fi
  sudo chmod -R 777 $final_path/$i
done

# Set permissions to ttrss directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload

# Update database schema
sudo sudo -u www-data php ${final_path}/update.php --update-schema

sudo yunohost app setting $app skipped_uris -v "/public.php,/api"
